### ISSUE TITLE
add line coverage reporting for specs

### ISSUE THREAD

**Issue by stevenou** [InvisibleCommerce/shipped-shield-ios-sdk#13]
add coverage reporting for the test suite.

lower priority than android SDK

**Comment by hoyelo** [comment]
<img width="930" alt="Screen Shot 2022-05-25 at 18 15 17" src="https://user-images.githubusercontent.com/3202811/170239489-d3aabc0e-0031-498c-97a8-b28554b900e9.png">

**Comment by hoyelo** [comment]
![Screen Shot 2022-05-30 at 12 38 39](https://user-images.githubusercontent.com/3202811/170918174-00bad321-7adf-4dac-9e69-81e354033fc4.png)
