### ISSUE TITLE
3 widget variants

### ISSUE THREAD

**Issue by stevenou** [InvisibleCommerce/shipped-shield-ios-sdk#15]
we are adding a new "carbon offset" product (called "green"). we will now have configuration option for `shield: true/false`, and `green: true/false`. 

as a result there will be 3 versions of widget/modal:
1. shield only (current widget)
2. green only (new widget)
3. shield + green (new widget)

designs will be shared when they are ready. new API endpoints:
`/v1/shield_offers` (existing endpoint)
`/v1/green_offers` (new endpoint)
`/v1/offers` (new endpoint)

recommend using only `/v1/offers` endpoint which provides combined fee information. client is responsible for filtering out/ignoring fee if configuration is off (e.g. if `shield: false`, then client should ignore `shieldFee` from API). 

the rest of the SDK interface is basically the same. `greenFee` should be added to the callback object if configuration for `green` is enabled.

**Comment by stevenou** [comment]
@jasmineic please provide iOS designs for new widgets/modals.

**Comment by stevenou** [comment]
@catalin-invisible to help ensure interface/implementation is consistent between JS and mobile SDKs

**Comment by jasmineic** [comment]
We're keeping the existing `switch` button.

**Comment by hoyelo** [comment]
![Simulator Screen Shot - iPhone 12 - 2022-07-19 at 13 23 49](https://user-images.githubusercontent.com/3202811/179671524-304a1552-dd5c-492a-a360-b8765aedb1fd.png)
@jasmineic do we have any changes on this page?

**Comment by jasmineic** [comment]
Yes, there's minor copy update on the bottom. https://www.figma.com/file/ryeFqjwQeMqdFzL8a8hrFz/Shipped-%E2%80%A2-Design-System-(VD)?node-id=25959%3A29701

<img width="663" alt="Screen Shot 2022-07-19 at 6 26 09 AM" src="https://user-images.githubusercontent.com/93731199/179761694-7cff741d-d89e-4591-856a-3e7defd03203.png">

**Comment by hoyelo** [comment]
@jasmineic The existing Learn more modal is used for shipped Shield only. If it is Green or Green + Shield, I am not sure what kind of display it should be. The new design has a lot of changes, I'm not sure if I need to make it like this.
<img width="400" alt="Screen Shot 2022-07-20 at 11 00 29" src="https://user-images.githubusercontent.com/3202811/179886822-5d97f4cf-8a05-4da0-a6f1-13dde0ec8ba3.png">

**Comment by jasmineic** [comment]
@hoyelo final 3 variant designs.

https://www.figma.com/file/ryeFqjwQeMqdFzL8a8hrFz/Shipped-%E2%80%A2-Design-System-(VD)?node-id=26269%3A30371
