### ISSUE TITLE
images not showing on iOS SDK

### ISSUE THREAD

**Issue by stevenou** [InvisibleCommerce/shipped-shield-ios-sdk#17]
![Image from iOS (1)](https://user-images.githubusercontent.com/439931/181635680-b6953867-9e63-4cf8-937a-2bf172891063.png)

**Comment by hoyelo** [comment]
@stevenou  Tried CocoaPods, swift package manager, Carthage integration, all work and not reproduce this issue. I can figure out why if I know how the customer integrates the SDK.

**Comment by stevenou** [comment]
hmmm it's using cocoapods...

**Comment by stevenou** [comment]
ShippedShield (0.1.4)

**Comment by hoyelo** [comment]
<img width="1196" alt="Screen Shot 2022-08-02 at 13 43 24" src="https://user-images.githubusercontent.com/3202811/182300477-3eb417c0-2cb0-438a-a516-e905707d7646.png">

I've seen this happen in one situation. Please tell the merchant to make sure the Copy Pods Resources script is added. In fact, once you execute `Pod Install`, it will be automatically installed to your Target, but it may not have been installed on the correct target, or it may have been accidentally deleted, or it may be that the version of `CocoaPods` is too old.

So, please follow these steps to check:
1. Run `gem install cocoapods` to upgrade `CocoaPods`
2. Go the root folder of the project, and run `pod install`
3. Make sure the `Copy Pods Resources` script is generated for the project target (as the screenshot above)
4. Run it.
